import {
  ChartPieIcon,
  TruckIcon,
  UsersIcon,
  CurrencyDollarIcon,
  ClockIcon,
  CheckCircleIcon,
  HomeIcon,
  UserGroupIcon,
  ShieldCheckIcon,
  ClipboardDocumentListIcon,
  CheckBadgeIcon,
  XCircleIcon,
  CreditCardIcon,
  BanknotesIcon,
  DocumentTextIcon,
  SparklesIcon,
  GiftIcon,
  StarIcon,
  ChartBarIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowLeftIcon,
  ExclamationTriangleIcon,
  Bars3Icon,
  GlobeAltIcon,
  BellIcon,
  UserIcon,
  ChevronDownIcon,
  XMarkIcon,
  Bars3BottomLeftIcon,
  Cog6ToothIcon,
  ArrowRightOnRectangleIcon,
  PhoneIcon,
  ShieldExclamationIcon,
  DocumentCheckIcon,
  LifebuoyIcon,
  MagnifyingGlassIcon
} from '@heroicons/react/24/outline'

export const ICONS = {
  Dashboard: ChartPieIcon,
  Shipments: TruckIcon,
  Drivers: UsersIcon,
  Revenue: CurrencyDollarIcon,
  Pending: ClockIcon,
  Completed: CheckCircleIcon,
  Home: HomeIcon,
  UserGroup: UserGroupIcon,
  ShieldCheck: ShieldCheckIcon,
  ClipboardDocumentList: ClipboardDocumentListIcon,
  CheckBadge: CheckBadgeIcon,
  XCircle: XCircleIcon,
  CreditCard: CreditCardIcon,
  Banknotes: BanknotesIcon,
  DocumentText: DocumentTextIcon,
  Sparkles: SparklesIcon,
  Gift: GiftIcon,
  Star: StarIcon,
  ChartBar: ChartBarIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ArrowLeft: ArrowLeftIcon,
  ExclamationTriangle: ExclamationTriangleIcon,
  Menu: Bars3Icon,
  Globe: GlobeAltIcon,
  Bell: BellIcon,
  User: UserIcon,
  ChevronDown: ChevronDownIcon,
  XMark: XMarkIcon,
  MenuOpen: Bars3BottomLeftIcon,
  Settings: Cog6ToothIcon,
  Logout: ArrowRightOnRectangleIcon,
  Phone: PhoneIcon,
  PrivacyPolicy: ShieldExclamationIcon,
  TermsConditions: DocumentCheckIcon,
  SupportContact: LifebuoyIcon,
  Search: MagnifyingGlassIcon
}
