export const KNOW_CHAMP_CATEGORIES = [
  {
    name: 'General Knowledge',
    icon: '📚',
    image: '/cat-general.png',
    colorClass: 'text-red-500 bg-red-500/10 border-red-500/20',
    borderGlowClass: 'hover:border-red-500/50 hover:shadow-[0_0_20px_rgba(239,68,68,0.25)]',
  },
  {
    name: 'Science',
    icon: '🔬',
    image: '/cat-science.png',
    colorClass: 'text-teal-400 bg-teal-400/10 border-teal-400/20',
    borderGlowClass: 'hover:border-teal-400/50 hover:shadow-[0_0_20px_rgba(45,212,191,0.25)]',
  },
  {
    name: 'Current Affairs',
    icon: '📰',
    image: '/cat-current.png',
    colorClass: 'text-purple-400 bg-purple-400/10 border-purple-400/20',
    borderGlowClass: 'hover:border-purple-400/50 hover:shadow-[0_0_20px_rgba(192,132,252,0.25)]',
  },
  {
    name: 'Sports',
    icon: '⚽',
    image: '/cat-sports.png',
    colorClass: 'text-orange-400 bg-orange-400/10 border-orange-400/20',
    borderGlowClass: 'hover:border-orange-400/50 hover:shadow-[0_0_20px_rgba(251,146,60,0.25)]',
  },
  {
    name: 'Entertainment',
    icon: '🎬',
    image: '/cat-entertainment.png',
    colorClass: 'text-pink-400 bg-pink-400/10 border-pink-400/20',
    borderGlowClass: 'hover:border-pink-400/50 hover:shadow-[0_0_20px_rgba(244,114,182,0.25)]',
  },
  {
    name: 'Technology',
    icon: '💻',
    image: '/cat-technology.png',
    colorClass: 'text-blue-400 bg-blue-400/10 border-blue-400/20',
    borderGlowClass: 'hover:border-blue-400/50 hover:shadow-[0_0_20px_rgba(96,165,250,0.25)]',
  },
  {
    name: 'History',
    icon: '📜',
    image: '/cat-history.png',
    colorClass: 'text-amber-600 bg-amber-600/10 border-amber-600/20',
    borderGlowClass: 'hover:border-amber-600/50 hover:shadow-[0_0_20px_rgba(217,119,6,0.25)]',
  },
];

export const KNOW_CHAMP_CONTESTS = [
  {
    category: 'General Knowledge',
    title: 'Mega GK Battle',
    prize: 50000,
    entry: 20,
    joined: 2450,
    maxPlayers: 5000,
    image: '/cat-general.png',
    date: '22 July 2026, 8:00 Am',
  },
  {
    category: 'Science',
    title: 'Science Champions',
    prize: 30000,
    entry: 15,
    joined: 1200,
    maxPlayers: 2000,
    image: '/cat-science.png',
    date: '23 July 2026, 10:00 Am',
  },
  {
    category: 'Current Affairs',
    title: 'Current Affairs Quiz',
    prize: 20000,
    entry: 5,
    joined: 3800,
    maxPlayers: 5000,
    image: '/cat-current.png',
    date: '24 July 2026, 9:00 Am',
  },
  {
    category: 'Sports',
    title: 'Sports Mania',
    prize: 25000,
    entry: 20,
    joined: 850,
    maxPlayers: 1000,
    image: '/cat-sports.png',
    date: '25 July 2026, 11:00 Am',
  },
  {
    category: 'Technology',
    title: 'Tech Titans',
    prize: 40000,
    entry: 10,
    joined: 1950,
    maxPlayers: 3000,
    image: '/cat-technology.png',
    date: '26 July 2026, 7:00 Am',
  },
];

export const KNOW_CHAMP_WINNERS = [
  {
    name: 'Rahul Sharma',
    amount: 100000,
    contest: 'Mega GK Battle',
    rank: 1,
    image: '/winners1.jpg',
  },
  {
    name: 'Priya Verma',
    amount: 75000,
    contest: 'Science Champions',
    rank: 2,
    image: '/winners2.jpg',
  },
  {
    name: 'Amit Kumar',
    amount: 50000,
    contest: 'Current Affairs Quiz',
    rank: 3,
    image: '/winners3.jpg',
  },
  {
    name: 'Shreya Gaikwad',
    amount: 80000,
    contest: 'Tech Titans',
    rank: 1,
    image: '/winners4.jpg',
  },
  {
    name: 'Vijay Singh',
    amount: 35000,
    contest: 'Sports Mania',
    rank: 2,
    image: '/winners5.jpg',
  },
];

export const KNOW_CHAMP_TESTIMONIALS = [
  {
    rating: 5,
    text: 'KnowChamp made learning extremely fun! The interface is so smooth and interactive, and winning cash prizes while testing my knowledge is just awesome. Highly recommend it to anyone who loves to learn!',
    name: 'Priya Verma',
    title: 'Active Learner',
    image: '/winners2.jpg',
  },
  {
    rating: 5,
    text: "I've tried several quiz platforms, but KnowChamp stands out. Its fair rules, quick payouts, and diverse quiz topics are perfect. I play it with my family and friends.",
    name: 'Amit Kumar',
    title: 'Quiz Enthusiast',
    image: '/winners3.jpg',
  },
  {
    rating: 5,
    text: "The live quiz experience is fantastic. The questions are challenging yet fair, and the leaderboard updates in real-time. I've recommended it to all my peers.",
    name: 'Shreya Gaikwad',
    title: 'Tech Titan Winner',
    image: '/winners4.jpg',
  },
];
